import 'package:flutter/material.dart';
import 'package:get_storage/get_storage.dart';

class LanguageProvider with ChangeNotifier {
  final box = GetStorage();
  bool isAr = false;

  Map<String, String> arLan = {
    'ProfileLabel': 'الملف الشخصي',
    'ReportLabel': 'إبلاغ عن مشكلة',
    'AddReport': 'إضافة الشكوى',
    'AddFileLabel': 'اضافة ملف  لمادة',
    'AddNewsLabel': 'اضافة خبر',
    'AddPhotoLabel': 'اضافة صورة الى المعرض',
    'AddMarksLabel': 'اضافة ملف علامات',
    'DeleteLabel': 'صفحة الحذف',
    'ReportListLabel': 'صندوق الشكاوي',
    'SettingLabel': 'الاعدادات',
    'HomeLabel': 'الصفحة الرئيسية',
    'SubjectsLabel': 'المواد',
    'ChatLabel': 'المحادثة الجماعية',
    'GalleryLabel': 'معرض الصور',
    'MarksLabel': 'المحصلات',
    'NewsLabel': 'الاخبار',
    'AboutLabel': 'حول',
    'Semester1': 'الفصل الاول',
    'Semester2': 'الفصل الثاني',
    'AboutUsLabel': 'من نحن',
    'AppDescribe':
        'تطبيق الطالب: هو تطبيق مخصص لطلاب الكلية التطبيقية في جامعة دمشق , للإختصاصين تقنيات حاسوب وميكاترونيكس , صمم من قبل الطلاب: أسامة خضر, أحمد خولاني, عبدالله عبدالرحمن, رشيد عبد الرحمن بإشراف: المهندسة إيمان وصفاء',
    'ChatGroupLabel': 'المحادثة الجماعية',
    'DownLabel': 'المواد المحملة',
    'FilesLabel': 'الملفات لمادة',
    'FilesEmpty': 'لا يوجد ملفات لهذه المادة بعد',
    'MarksEmpty': 'لا يوجد محصلات لإظهارها',
    'NameReport': 'لن يعرف كاتب الرسالة هذه أبدا'
        ' ستظهر هذه الشكوى لدينا بأسم مجهول.',
    'GalleryCollegeLabel': 'معرض الصور',
    'PhotoLabel': 'صورة',
    'ChooseSemester': 'إختر فصل',
    'FromYear': 'من السنة',
    'At': 'في قسم',
    'CompDep': 'تقنيات حاسوب',
    'MechDep': 'ميكاترونيكس',
    'DarkMode': 'الوضع المظلم',
    'EnDarkMode': 'تفعيل الوضع المظلم',
    'ArabicLang': 'اللغة العربية',
    'EnArabicLang': 'جعل لغة التطبيق هي اللغة الانكليزية',
    'PrimaryColor': 'إختر اللون الثانوي',
    'Today': 'اليوم',
    'Msg': 'الرسالة',
    'AddedLatest': 'الملفات المضافة حديثا',
    'Greeting': 'مرحبا,',
    'Welcoming': 'أهلا بك',
    'NewsLatest': 'آخر  الاخبار',
    'Logout': 'تسجيل الخروج',
    'Empty': 'لا شي جديد',
    'Email': 'البريد الإلتكروني',
    'Password': 'كلمة المرور',
    'Login': 'تسجيل الدخول',
    'YouDontHaveAccount': 'ليس  لديك  حساب؟',
    'SignUp': 'إنشاء حساب',
    'ChoosingPicture': 'اختر صورة',
    'FullName': 'الأسم الكامل',
    'FirstName': 'الاسم الأول',
    'LastName': 'الاسم الاخير',
    'ConfirmPassword': 'تأكيد كلمة المرور',
    'CreatedAccount': 'تم إنشاء الحساب',
    'YouHaveAccount': 'لديك حساب؟',
    'WhichDepartment': 'إختر الإختصاص',
    'WhichYear': 'إختر السنة الدراسية',
    '1st': 'السنة الاولى',
    '2nd': 'السنة الثانية',
    '3rd': 'السنة الثالثة',
    '4th': 'السنة الرابعة',
    'AC': 'الكلية التطبيقية',
    'StudentApp': 'تطبيق الطالب',
    'AdminPanel': 'لائحة المشرف',
    'ReportText': 'المشكلة او الشكوى',
    'enChat': 'تفعيل المحادثة',
    'enChatSub': 'تفعيل/إلغاء التفعيل المحادثة للاعضاء الغير المشرفين',
  };
  Map<String, String> enLan = {
    'ProfileLabel': 'Profile',
    'AddFileLabel': 'Add File',
    'AddReport': 'Add Report',
    'NameReport': 'Share your report as unknown,'
        ' we will never know who write this report ',
    'ReportLabel': 'Report',
    'AddNewsLabel': 'Add News',
    'AddPhotoLabel': 'Add Image',
    'AddMarksLabel': 'Add Marks',
    'DeleteLabel': 'Delete Objects',
    'SettingLabel': 'Setting',
    'ReportListLabel': 'Report Box',
    'HomeLabel': 'Home',
    'SubjectsLabel': 'Subjects',
    'ChatLabel': 'Chat',
    'GalleryLabel': 'Gallery',
    'MarksLabel': 'Marks',
    'NewsLabel': 'News',
    'AboutLabel': 'About',
    'Semester1': 'Semester 1',
    'Semester2': 'Semester 2',
    'AboutUsLabel': 'About us',
    'AppDescribe': 'Student app for the Applied College students \n \n'
        ' designed and developed by the students \n '
        '1. Ahmad Kholani \n 2. Abdullah Abdulrahman \n '
        '3. Ossama Khader \n 4. Rasheed Abdulrahamn  ',
    'ChatGroupLabel': 'Chat group',
    'DownLabel': 'Failed subjects',
    'FilesLabel': 'Files for',
    'FilesEmpty': 'Sorry, There is no files here',
    'MarksEmpty': 'Sorry, There is no marks here',
    'GalleryCollegeLabel': 'College gallery',
    'PhotoLabel': 'Photo',
    'ChooseSemester': 'Choose a semester',
    'FromYear': 'from year',
    'At': 'at',
    'CompDep': 'Computer Technology Department',
    'MechDep': 'Mechatronics Department',
    'DarkMode': 'Dark mode',
    'EnDarkMode': 'enable dark mode',
    'ArabicLang': 'Arabic Language',
    'EnArabicLang': 'make application language arabic',
    'PrimaryColor': 'Choose primary color',
    'Today': 'Today',
    'Msg': 'Message',
    'AddedLatest': 'Recently Added',
    'Greeting': 'Hey,',
    'Welcoming': 'Welcome back',
    'NewsLatest': 'Latest News',
    'Logout': 'Logout',
    'Empty': 'nothing new',
    'Email': 'Email',
    'Password': 'Password',
    'Login': 'Login',
    'YouDontHaveAccount': 'You don\'t have account?',
    'SignUp': 'Sign up',
    'ChoosingPicture': 'Choose a picture',
    'FullName': 'Full name',
    'FirstName': 'First name',
    'LastName': 'Last name',
    'ConfirmPassword': 'Confirm password',
    'CreatedAccount': 'Created account',
    'YouHaveAccount': 'You have account?',
    'WhichDepartment': 'Which Department',
    'WhichYear': 'Which Year',
    '1st': '1st year',
    '2nd': '2nd year',
    '3rd': '3rd year',
    '4th': '4th year',
    'AC': 'Applied College',
    'StudentApp': 'Student App',
    'AdminPanel': 'Admin Panel',
    'ReportText': 'Report the problem',
    'enChat': 'enable chat',
    'enChatSub': 'enable/disable chat for who is not admin',
  };

  changLanguage() {
    isAr = !isAr;
    box.write('isAr', isAr);
    notifyListeners();
  }

  String? get(String key) {
    return isAr ? arLan[key] : enLan[key];
  }

  Future getIsAr() async {
    isAr = await box.read('isAr');
    notifyListeners();
  }
}
